name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run Jest Test Suite
      run: npm test
    
    - name: Publish Test Report
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: test-results/**/results.xml